# Generated by Django 3.0.3 on 2020-02-15 19:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=2000)),
                ('author', models.CharField(max_length=255)),
                ('stock', models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
    ]
