# Generated by Django 3.0.3 on 2020-02-16 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20200216_0057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='subject',
            new_name='author',
        ),
    ]
