# Generated by Django 3.0.3 on 2020-02-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_auto_20200215_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='book',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='to_date',
        ),
        migrations.AddField(
            model_name='loan',
            name='notes',
            field=models.TextField(max_length=4000, null=True),
        ),
    ]
