# Generated by Django 3.0.3 on 2020-02-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_auto_20200216_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='notes',
            field=models.TextField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
