# Generated by Django 3.0.3 on 2020-02-15 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_auto_20200215_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='created_by',
        ),
    ]
