# Generated by Django 3.0.3 on 2020-02-15 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0008_remove_loan_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='loan_start',
            new_name='loan_starts',
        ),
        migrations.AddField(
            model_name='loan',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
