# Generated by Django 3.0.3 on 2020-02-15 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0009_auto_20200215_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='book',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='loan_ends',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='loan_starts',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='student',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='subject',
        ),
    ]
