# Generated by Django 3.0.3 on 2020-02-15 23:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0001_initial'),
        ('subjects', '0002_auto_20200215_1704'),
        ('loans', '0010_auto_20200215_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='books.Book'),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_ends',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_starts',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='loan',
            name='student',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Student'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='subjects.Subject'),
        ),
    ]
