# Generated by Django 3.0.3 on 2020-02-15 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subjects', '0002_auto_20200215_1704'),
        ('loans', '0011_auto_20200215_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='student',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Student'}, on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loan',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='subjects.Subject'),
        ),
    ]
